package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	version = "v0.0.1"
	suffix  = "_http.pb.go"
)

func main() {
	showVersion := flag.Bool("version", false, "print the version and exit")

	flag.Parse()

	if *showVersion {
		fmt.Printf("protoc-gen-og %s\n", version)
		return
	}

	var flags flag.FlagSet

	protoValidate := flags.Bool("proto_validate", false, "generate request validation using protovalidate")

	protogen.Options{
		ParamFunc: flags.Set,
	}.Run(func(p *protogen.Plugin) error {
		p.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range p.Files {
			if !f.Generate {
				continue
			}
			genServiceFile(p, f, *protoValidate)
			genCodeFile(p, f)
			genCodeJson(p, f)
		}
		return nil
	})
}

const (
	ctxPkg      = protogen.GoImportPath("context")
	errorPkg    = protogen.GoImportPath("errors")
	httpPkg     = protogen.GoImportPath("net/http")
	chiPkg      = protogen.GoImportPath("github.com/go-chi/chi/v5")
	helperPkg   = protogen.GoImportPath("github.com/noble-gase/neon/helper")
	resultPkg   = protogen.GoImportPath("github.com/noble-gase/neon/result")
	restyPkg    = protogen.GoImportPath("github.com/go-resty/resty/v2")
	codekitPkg  = protogen.GoImportPath("github.com/noble-gase/neon/codekit")
	protokitPkg = protogen.GoImportPath("github.com/noble-gase/neon/protokit")
)

func protocVersion(p *protogen.Plugin) string {
	v := p.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}

	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

// generateFile generates a `xxx_http.pb.go` file containing HTTP service definitions.
func genServiceFile(p *protogen.Plugin, f *protogen.File, pv bool) {
	if len(f.Services) == 0 {
		return
	}

	filename := f.GeneratedFilenamePrefix + suffix
	gf := p.NewGeneratedFile(filename, f.GoImportPath)

	gf.P("// Code generated by protoc-gen-og. DO NOT EDIT.")
	gf.P("// versions:")
	gf.P("// - protoc-gen-og ", version)
	gf.P("// - protoc           ", protocVersion(p))
	if f.Proto.GetOptions().GetDeprecated() {
		gf.P("// ", f.Desc.Path(), " is deprecated.")
	} else {
		gf.P("// source: ", f.Desc.Path())
	}
	gf.P()
	gf.P("package ", f.GoPackageName)
	gf.P()

	genFileContent(f, gf, pv)
}

// generateFileContent generates the HTTP service definitions, excluding the package statement.
func genFileContent(f *protogen.File, gf *protogen.GeneratedFile, pv bool) {
	for _, service := range f.Services {
		genService(gf, service, pv)
	}
}

func genService(gf *protogen.GeneratedFile, service *protogen.Service, pv bool) {
	serverType := service.GoName + "HttpServer"
	// Server interface
	genServerInterface(gf, service, serverType)
	gf.P()
	// Unimplemented HttpServer
	genServerUnimplement(gf, service, serverType)
	gf.P()
	// Register Router
	genRouterRegister(gf, service, serverType)
	// HttpServer Methods
	genServerMethods(gf, service, serverType, pv)
	gf.P()
	gf.P("// --------------------------------------------- http client ---------------------------------------------")
	gf.P()
	// Client interface
	clientType := service.GoName + "HttpClient"
	// Client interface
	genClientInterface(gf, service, clientType)
	gf.P()
	// New HttpClient
	genClientNew(gf, service, clientType)
	// Register HttpClient methods
	genClientMethods(gf, service, clientType)
	gf.P()
}

// Method(ctx context.Context, in *XXXRequest) (*XXXResponse, error)
func serverSignature(gf *protogen.GeneratedFile, method *protogen.Method) string {
	var reqArgs []string
	// params
	reqArgs = append(reqArgs, "ctx "+gf.QualifiedGoIdent(ctxPkg.Ident("Context")))
	reqArgs = append(reqArgs, "in *"+gf.QualifiedGoIdent(method.Input.GoIdent))
	// return
	resp := "(*" + gf.QualifiedGoIdent(method.Output.GoIdent) + ", error)"
	return method.GoName + "(" + strings.Join(reqArgs, ", ") + ") " + resp
}

func genServerInterface(gf *protogen.GeneratedFile, service *protogen.Service, serviceType string) {
	gf.P("// ", serviceType, " is the server API definition for ", service.GoName)
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		gf.P("// ", service.GoName, " is deprecated.")
	}
	gf.AnnotateSymbol(serviceType, protogen.Annotation{Location: service.Location})
	// type XXXHttpServer interface {
	gf.P("type ", serviceType, " interface {")
	for _, m := range service.Methods {
		if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
			continue
		}
		gf.AnnotateSymbol(serviceType+"."+m.GoName, protogen.Annotation{Location: m.Location})
		if v, ok := m.Desc.Options().(*descriptorpb.MethodOptions); ok && v.GetDeprecated() {
			gf.P("// ", m.GoName, " is deprecated.")
		}
		gf.P(m.Comments.Leading, serverSignature(gf, m))
	}
	gf.P("}")
}

func genServerUnimplement(gf *protogen.GeneratedFile, service *protogen.Service, serviceType string) {
	gf.P("// Unimplemented", serviceType, " should be embedded to have")
	gf.P("// forward compatible implementations.")
	gf.P("//")
	gf.P("// NOTE: this should be embedded by value instead of pointer to avoid a nil")
	gf.P("// pointer dereference when methods are called.")
	gf.P("type Unimplemented", serviceType, " struct{}")
	for _, m := range service.Methods {
		gf.P()
		gf.P("func (Unimplemented", serviceType, ")", m.GoName, "(context.Context, *", m.Input.GoIdent, ") (*", m.Output.GoIdent, ", error) {")
		gf.P(`return nil,`, errorPkg.Ident("New"), `("method `, m.GoName, ` not implemented")`)
		gf.P("}")
	}
}

func genRouterRegister(gf *protogen.GeneratedFile, service *protogen.Service, serviceType string) {
	gf.P("func Register", serviceType, "(r ", chiPkg.Ident("Router"), ", svc ", serviceType, ") {")
	for _, method := range service.Methods {
		comment := strings.TrimPrefix(method.Comments.Leading.String(), "//")
		comment = strings.TrimSpace(strings.TrimSuffix(comment, "\n"))

		routers := getHttpRouters(method)
		for _, router := range routers {
			gf.P("// ", router.Method, " | ", comment)
			gf.P(`r.Method("`, router.Method, `","`, router.Path, `", _`, service.GoName, "_", method.GoName, `(svc))`)
		}
	}
	gf.P("}")
}

func genServerMethods(gf *protogen.GeneratedFile, service *protogen.Service, serviceType string, pv bool) {
	for _, m := range service.Methods {
		gf.P()
		gf.P(strings.TrimSuffix(m.Comments.Leading.String(), "\n"))
		gf.P("func _", service.GoName, "_", m.GoName, "(svc ", serviceType, ") http.HandlerFunc {")
		gf.P("return func(w ", httpPkg.Ident("ResponseWriter"), ", r *", httpPkg.Ident("Request"), ") {")
		gf.P("ctx := r.Context()")
		gf.P()
		gf.P("// parse request")
		gf.P("req := new(", m.Input.GoIdent, ")")
		gf.P("if err := ", helperPkg.Ident("BindProto"), "(r, req, ", pv, "); err != nil {")
		gf.P(resultPkg.Ident("Err"), "(", codekitPkg.Ident("FromError"), "(err)).JSON(w, r)")
		gf.P("return")
		gf.P("}")
		gf.P()
		gf.P("// call service")
		gf.P("resp, err := svc.", m.GoName, "(ctx, req)")
		gf.P("if err != nil {")
		gf.P(resultPkg.Ident("Err"), "(err).JSON(w, r)")
		gf.P("return")
		gf.P("}")
		gf.P(resultPkg.Ident("OK"), "(resp).JSON(w, r)")
		gf.P("}")
		gf.P("}")
	}
}

// Method(ctx context.Context, in *XXXRequest, header ...http.Header) (*MethodResp, error)
func clientSignature(gf *protogen.GeneratedFile, method *protogen.Method) string {
	var reqArgs []string
	// params
	reqArgs = append(reqArgs, "ctx "+gf.QualifiedGoIdent(ctxPkg.Ident("Context")))
	reqArgs = append(reqArgs, "in *"+gf.QualifiedGoIdent(method.Input.GoIdent))
	reqArgs = append(reqArgs, "header ..."+gf.QualifiedGoIdent(httpPkg.Ident("Header")))
	// return
	resp := "(*" + gf.QualifiedGoIdent(method.Output.GoIdent) + ", error)"
	return method.GoName + "(" + strings.Join(reqArgs, ", ") + ") " + resp
}

func genClientInterface(gf *protogen.GeneratedFile, service *protogen.Service, serviceType string) {
	gf.P("// ", serviceType, " is the client API definition for ", service.GoName)
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		gf.P("// ", service.GoName, " is deprecated.")
	}
	gf.AnnotateSymbol(serviceType, protogen.Annotation{Location: service.Location})
	// type XXXHttpClient interface {
	gf.P("type ", serviceType, " interface {")
	for _, m := range service.Methods {
		if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
			continue
		}
		gf.AnnotateSymbol(serviceType+"."+m.GoName, protogen.Annotation{Location: m.Location})
		if v, ok := m.Desc.Options().(*descriptorpb.MethodOptions); ok && v.GetDeprecated() {
			gf.P("// ", m.GoName, " is deprecated.")
		}
		gf.P(m.Comments.Leading, clientSignature(gf, m))
	}
	gf.P("}")
}

func genClientNew(gf *protogen.GeneratedFile, _ *protogen.Service, serviceType string) {
	gf.P("type ", unexport(serviceType), " struct {")
	gf.P("client *", restyPkg.Ident("Client"))
	gf.P("}")
	gf.P()
	gf.P("// New", serviceType, " returns a client for ", serviceType)
	gf.P("func New", serviceType, "(hc *", httpPkg.Ident("Client"), ", baseURL string)", serviceType, "{")
	gf.P("c := ", restyPkg.Ident("NewWithClient"), "(hc)")
	gf.P("c.SetBaseURL(baseURL)")
	gf.P("return &", unexport(serviceType), "{client: c}")
	gf.P("}")
}

func genClientMethods(gf *protogen.GeneratedFile, service *protogen.Service, serviceType string) {
	for _, method := range service.Methods {
		routers := getHttpRouters(method)
		if len(routers) == 0 {
			continue
		}
		router := routers[0]

		gf.P()
		gf.P(strings.TrimSuffix(method.Comments.Leading.String(), "\n"))
		gf.P("func (c *", unexport(serviceType), ") ", method.GoName, "(ctx ", ctxPkg.Ident("Context"), ", in *", gf.QualifiedGoIdent(method.Input.GoIdent), ", header ...", httpPkg.Ident("Header"), ") (*"+gf.QualifiedGoIdent(method.Output.GoIdent)+", error) {")
		gf.P("ret := new(", protokitPkg.Ident("ApiResult[*"), gf.QualifiedGoIdent(method.Output.GoIdent), "])")
		gf.P()
		gf.P("// build request")
		if router.Method == http.MethodPost || router.Method == http.MethodPut || router.Method == http.MethodPatch {
			gf.P("req := c.client.R().SetContext(ctx).SetBody(in).SetResult(ret)")
		} else {
			gf.P("req := c.client.R().SetContext(ctx).SetQueryParamsFromValues(", protokitPkg.Ident("MessageToValues"), "(in)).SetResult(ret)")
		}
		gf.P("if len(header) != 0 {")
		gf.P("req.SetHeaderMultiValues(header[0])")
		gf.P("}")
		gf.P()
		gf.P("// send request")
		gf.P(`resp, err := req.Execute("`, router.Method, `","`, router.Path, `")`)
		gf.P("if err != nil {")
		gf.P("return nil, err")
		gf.P("}")
		gf.P("if resp.StatusCode() !=", httpPkg.Ident("StatusOK"), "{")
		gf.P("return nil,", errorPkg.Ident("New"), "(resp.Status())")
		gf.P("}")
		gf.P("if err = ret.Error(0); err != nil {")
		gf.P("return nil, err")
		gf.P("}")
		gf.P("return ret.Data, nil")
		gf.P("}")
	}
}

type HttpRouter struct {
	Method   string
	Path     string
	Priority int
}

func getHttpRouters(method *protogen.Method) []*HttpRouter {
	rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
	if !ok || rule == nil {
		return nil
	}

	var routers []*HttpRouter
	if router := parseHttpRouter(rule); router != nil {
		routers = append(routers, router)
	}

	// additional bindings
	for _, ab := range rule.GetAdditionalBindings() {
		if router := parseHttpRouter(ab); router != nil {
			routers = append(routers, router)
		}
	}

	sort.SliceStable(routers, func(i, j int) bool {
		return routers[i].Priority < routers[j].Priority
	})
	return routers
}

func parseHttpRouter(rule *annotations.HttpRule) *HttpRouter {
	switch v := rule.Pattern.(type) {
	case *annotations.HttpRule_Post:
		return &HttpRouter{
			Method:   http.MethodPost,
			Path:     v.Post,
			Priority: 0,
		}
	case *annotations.HttpRule_Put:
		return &HttpRouter{
			Method:   http.MethodPut,
			Path:     v.Put,
			Priority: 1,
		}
	case *annotations.HttpRule_Patch:
		return &HttpRouter{
			Method:   http.MethodPatch,
			Path:     v.Patch,
			Priority: 2,
		}
	case *annotations.HttpRule_Get:
		return &HttpRouter{
			Method:   http.MethodGet,
			Path:     v.Get,
			Priority: 3,
		}
	case *annotations.HttpRule_Delete:
		return &HttpRouter{
			Method:   http.MethodDelete,
			Path:     v.Delete,
			Priority: 4,
		}
	case *annotations.HttpRule_Custom:
		return &HttpRouter{
			Method:   strings.ToUpper(v.Custom.GetKind()),
			Path:     v.Custom.GetPath(),
			Priority: 5,
		}
	default:
		return nil
	}
}

// genCodeFile generates a `code.pb.go` file containing HTTP service definitions.
func genCodeFile(p *protogen.Plugin, f *protogen.File) {
	if !strings.HasSuffix(f.Desc.Path(), "code.proto") || len(f.Enums) == 0 {
		return
	}

	filename := f.GeneratedFilenamePrefix + suffix
	gf := p.NewGeneratedFile(filename, f.GoImportPath)

	gf.P("// Code generated by protoc-gen-og. DO NOT EDIT.")
	gf.P("// versions:")
	gf.P("// - protoc-gen-og ", version)
	gf.P("// - protoc           ", protocVersion(p))
	if f.Proto.GetOptions().GetDeprecated() {
		gf.P("// ", f.Desc.Path(), " is deprecated.")
	} else {
		gf.P("// source: ", f.Desc.Path())
	}
	gf.P()
	gf.P("package ", f.GoPackageName)
	gf.P()

	genCodeContent(f, gf)
}

// genCodeContent generates the HTTP code definitions, excluding the package statement.
func genCodeContent(f *protogen.File, gf *protogen.GeneratedFile) {
	gf.P("var (")
	for _, e := range f.Enums {
		for _, v := range e.Values {
			msg := strings.ToLower(string(v.Desc.Name()))
			if comment := string(v.Comments.Trailing); len(comment) != 0 {
				for seq := range strings.SplitSeq(comment, ";") {
					if _, after, found := strings.Cut(seq, "="); found {
						msg = strings.TrimSpace(after)
						break
					}
				}
			}
			name := case2camel(string(v.Desc.Name()))
			gf.P(e.Desc.Name(), "_", name, "=", codekitPkg.Ident("New"), "(int(", e.Desc.Name(), "_", v.Desc.Name(), `), "`, msg, `")`)
		}
		gf.P()
	}
	gf.P(")")
	gf.P()
	for _, e := range f.Enums {
		for _, v := range e.Values {
			name := case2camel(string(v.Desc.Name()))
			gf.P("func Is_", e.Desc.Name(), "_", name, "(err error) bool {")
			gf.P("return ", codekitPkg.Ident("Is"), "(err, ", e.Desc.Name(), "_", name, ")")
			gf.P("}")
			gf.P()
		}
	}
}

func genCodeJson(p *protogen.Plugin, f *protogen.File) {
	if !strings.HasSuffix(f.Desc.Path(), "code.proto") || len(f.Enums) == 0 {
		return
	}

	m := make(map[string]map[string]string) // map[lang][code]msg

	for _, e := range f.Enums {
		for _, v := range e.Values {
			key := strconv.Itoa(int(v.Desc.Number()))
			if comment := string(v.Comments.Trailing); len(comment) != 0 {
				for seq := range strings.SplitSeq(comment, ";") {
					if before, after, found := strings.Cut(seq, "="); found {
						lang := strings.TrimSpace(before)
						msg := strings.TrimSpace(after)
						if _, ok := m[lang]; !ok {
							m[lang] = make(map[string]string)
						}
						m[lang][key] = msg
					}
				}
			}
		}
	}

	for lang, codes := range m {
		filename := f.GeneratedFilenamePrefix + "_" + lang + ".json"
		b, _ := json.MarshalIndent(codes, "", "  ")
		gf := p.NewGeneratedFile(filename, f.GoImportPath)
		gf.P(string(b))
	}
}

func case2camel(s string) string {
	s = strings.ToLower(s)
	items := strings.Split(s, "_")
	count := len(items)
	if count == 1 {
		return export(s)
	}
	for i := range count {
		items[i] = export(items[i])
	}
	return strings.Join(items, "")
}

func export(s string) string { return strings.ToUpper(s[:1]) + s[1:] }

func unexport(s string) string { return strings.ToLower(s[:1]) + s[1:] }
